spring:
  application:
    name: order-service
    
#server:
  #port: 8201
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka1:2002/eureka
#启用feign熔断和服务降级功能
feign:
  hystrix:
    enabled: true
#设置暴露监控点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
#设置rabbitmq端口
spring:
  rabbitmq:
    host: 192.168.194.130
    port: 5672
    username: admin
    password: admin
---
spring:
  profiles: order1
  
server:
  port: 8201
---
spring:
  profiles: order2

server:
  port: 8202